language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=fdabrandao
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install urllib3[secure] --upgrade
  - python updatelib.py
  - $PIP install cibuildwheel==0.7.2
  - cibuildwheel --output-dir wheelhouse

after_success:
  - $PIP install install twine
  - python -m twine upload wheelhouse/*.whl || true
