environment:
  TWINE_USERNAME: fdabrandao
  # Note: TWINE_PASSWORD is set in Appveyor settings
build_script:
  - python updatelib.py
  - pip install cibuildwheel==0.4.0
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      } else {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
