jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  strategy:
    matrix:
      x86:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
        CIBW_MANYLINUX_I686_IMAGE: manylinux1
        CIBW_SKIP: pp*
      ppc64le:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_SKIP: cp27-manylinux*
        CIBW_BUILD: pp*
  env:
    CIBW_MANYLINUX_X86_64_IMAGE: $(CIBW_MANYLINUX_X86_64_IMAGE)
    CIBW_MANYLINUX_I686_IMAGE: $(CIBW_MANYLINUX_I686_IMAGE)
    CIBW_SKIP: $(CIBW_SKIP)
    CIBW_BUILD: $(CIBW_BUILD)
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cibuildwheel==1.5.1
        python3 updatelib.py
        cibuildwheel --platform linux --output-dir wheelhouse .
        python3 -m pip install twine
        twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) wheelhouse/*.whl || exit 0
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cibuildwheel==1.5.1
        python3 updatelib.py
        cibuildwheel --platform macos --output-dir wheelhouse .
        python3 -m pip install twine
        twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) wheelhouse/*.whl || exit 0
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
    - task: UsePythonVersion@0
    - script: choco install vcpython27 -f -y
      displayName: Install Visual C++ for Python 2.7
    - bash: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel==1.5.1
        python updatelib.py
        cibuildwheel --platform windows --output-dir wheelhouse .
        python -m pip install twine
        twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) wheelhouse/*.whl || exit 0
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}